#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_


#define IEEE802154_CONF_DEFAULT_CHANNEL 20

#define IEEE802154_CONF_PANID 0xCAFE

#define LOG_CONF_LEVEL_MAIN    LOG_LEVEL_INFO
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_DBG

#endif /* PROJECT_CONF_H_ */