CONTIKI_PROJECT = temp-sensor
all: $(CONTIKI_PROJECT)

CONTIKI = ../../contiki-ng

MAKE_MAC = MAKE_MAC_NULLMAC
MAKE_NET = MAKE_NET_NULLNET
MAKE_ROUTING = MAKE_ROUTING_NULLROUTING

include $(CONTIKI)/Makefile.include
include $(CONTIKI/Makefile.identify-target)
